"""
Model Training Script
Train Isolation Forest models for KYC, Business, and Transaction anomaly detection

This script has been updated to work with the actual data structure generated by
generate_synthetic_data.py. It supports training multiple model types:

1. KYC Model: Trains on customer demographic and identity data
2. Business Model: Trains on business information and financial data
3. Transaction Model: Trains on transaction patterns and behaviors
4. Merged Model: Combines KYC and Business features for comprehensive analysis

Usage Examples:
    # Train all models (hackathon demo mode)
    python train_models.py

    # Train specific models
    python train_models.py --train-kyc --kyc-data data/raw/kyc_training_data.csv
    python train_models.py --train-business --business-data data/raw/business_training_data.csv
    python train_models.py --train-transaction --transaction-data data/raw/transaction_training_data.csv
    python train_models.py --train-merged --merged-data data/raw/kyc_business_training_data.csv

    # Train multiple models
    python train_models.py --train-kyc --train-business --kyc-data data/raw/kyc_training_data.csv --business-data data/raw/business_training_data.csv
"""
import sys
import os

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
from sklearn.ensemble import IsolationForest  # noqa: E402
from sklearn.preprocessing import StandardScaler  # noqa: E402
import joblib  # noqa: E402
import argparse  # noqa: E402
from pathlib import Path  # noqa: E402

from app.core.config import settings  # noqa: E402


def load_training_data(data_path: str, data_type: str):
    """
    Load training data from CSV
    
    Args:
        data_path: Path to CSV file
        data_type: 'kyc' or 'transaction'
    """
    print(f"Loading {data_type} training data from {data_path}")
    df = pd.read_csv(data_path)
    print(f"Loaded {len(df)} records")
    return df


def prepare_kyc_features(df: pd.DataFrame) -> np.ndarray:
    """Extract KYC features from the actual generated data structure"""
    # Create derived features from the available KYC data
    features = []
    
    # Age feature
    features.append(df['customer_age'].values)
    
    # Gender encoding (0 for male, 1 for female)
    gender_encoded = (df['customer_gender'] == 'female').astype(int)
    features.append(gender_encoded.values)
    
    # Marital status encoding
    marital_mapping = {'single': 0, 'married': 1, 'divorced': 2, 'widowed': 3}
    marital_encoded = df['customer_marital_status'].map(marital_mapping).fillna(-1)
    features.append(marital_encoded.values)
    
    # Education level encoding
    education_mapping = {'primary': 0, 'secondary': 1, 'tertiary': 2, 'post_graduate': 3}
    education_encoded = df['customer_education_level'].map(education_mapping).fillna(-1)
    features.append(education_encoded.values)
    
    # Region encoding (simplified - just use region diversity)
    region_encoded = pd.Categorical(df['customer_region']).codes
    features.append(region_encoded)
    
    # City encoding
    city_encoded = pd.Categorical(df['customer_city']).codes
    features.append(city_encoded)
    
    # Zone encoding
    zone_encoded = pd.Categorical(df['customer_zone_or_sub_city']).codes
    features.append(zone_encoded)
    
    # Woreda as numeric (handle non-numeric values)
    woreda_numeric = pd.to_numeric(df['customer_woreda'], errors='coerce').fillna(0)
    features.append(woreda_numeric.values)
    
    # Phone number patterns (last 4 digits as feature)
    phone_last_4 = df['customer_phone_number'].astype(str).str[-4:].astype(int)
    features.append(phone_last_4.values)
    
    # TIN number patterns (length and character diversity)
    tin_length = df['customer_tin_number'].str.len()
    features.append(tin_length.values)
    
    # Bank account patterns
    account_length = df['customer_bank_account_number'].str.len()
    features.append(account_length.values)
    
    return np.column_stack(features)


def prepare_transaction_features(df: pd.DataFrame) -> np.ndarray:
    """Extract transaction features from the actual generated data structure"""
    features = []
    
    # Credit amount
    features.append(df['credit'].values)
    
    # Debit amount
    features.append(df['debit'].values)
    
    # Closing balance
    features.append(df['closingBalance'].values)
    
    # Source encoding
    source_mapping = {
        'CASH DEPOSIT': 0, 'FUND TRANSFER': 1, 'CASH WITHDRAW': 2, 
        'TELE BIRR INCOMING': 3, 'TELE BIRR OUT GOING': 4, 
        'ATM card subscription fee': 5
    }
    source_encoded = df['source'].map(source_mapping).fillna(-1)
    features.append(source_encoded.values)
    
    # Narrative length (as a feature for pattern detection)
    narrative_length = df['narrative'].str.len()
    features.append(narrative_length.values)
    
    # Transaction amount (credit - debit)
    transaction_amount = df['credit'] - df['debit']
    features.append(transaction_amount.values)
    
    # Balance ratio (transaction amount / closing balance)
    balance_ratio = np.where(df['closingBalance'] > 0, 
                            transaction_amount / df['closingBalance'], 
                            0)
    features.append(balance_ratio)
    
    # Date features (extract from date string)
    df['date'] = pd.to_datetime(df['date'])
    features.append(df['date'].dt.hour.values)  # Hour of day
    features.append(df['date'].dt.dayofweek.values)  # Day of week
    features.append(df['date'].dt.day.values)  # Day of month
    features.append(df['date'].dt.month.values)  # Month
    
    # Transaction frequency per customer (grouped)
    customer_txn_counts = df.groupby('customer_id').size()
    features.append(df['customer_id'].map(customer_txn_counts).values)
    
    return np.column_stack(features)


def prepare_customer_features(df: pd.DataFrame) -> np.ndarray:
    """
    Extract customer-level features from transaction data
    
    This creates aggregated features per customer that capture their overall
    transaction behavior patterns for customer-level fraud detection.
    """
    print("Preparing customer-level features...")
    
    # Group by customer_id and calculate aggregated features
    customer_features = []
    customer_ids = []
    
    for customer_id, customer_df in df.groupby('customer_id'):
        customer_ids.append(customer_id)
        features = []
        
        # Basic transaction counts and amounts
        total_transactions = len(customer_df)
        features.append(total_transactions)
        
        # Amount statistics
        total_credit = customer_df['credit'].sum()
        total_debit = customer_df['debit'].sum()
        avg_credit = customer_df['credit'].mean()
        avg_debit = customer_df['debit'].mean()
        max_credit = customer_df['credit'].max()
        max_debit = customer_df['debit'].max()
        
        features.extend([total_credit, total_debit, avg_credit, avg_debit, max_credit, max_debit])
        
        # Balance statistics
        avg_balance = customer_df['closingBalance'].mean()
        max_balance = customer_df['closingBalance'].max()
        min_balance = customer_df['closingBalance'].min()
        balance_volatility = customer_df['closingBalance'].std()
        
        features.extend([avg_balance, max_balance, min_balance, balance_volatility])
        
        # Transaction amount statistics
        transaction_amounts = customer_df['credit'] - customer_df['debit']
        avg_transaction_amount = transaction_amounts.mean()
        max_transaction_amount = transaction_amounts.max()
        min_transaction_amount = transaction_amounts.min()
        transaction_volatility = transaction_amounts.std()
        
        features.extend([avg_transaction_amount, max_transaction_amount, 
                        min_transaction_amount, transaction_volatility])
        
        # Source diversity and patterns
        source_counts = customer_df['source'].value_counts()
        unique_sources = len(source_counts)
        most_common_source_ratio = source_counts.iloc[0] / total_transactions if total_transactions > 0 else 0
        
        # Source-specific ratios
        cash_deposit_ratio = (customer_df['source'] == 'CASH DEPOSIT').sum() / total_transactions
        fund_transfer_ratio = (customer_df['source'] == 'FUND TRANSFER').sum() / total_transactions
        cash_withdraw_ratio = (customer_df['source'] == 'CASH WITHDRAW').sum() / total_transactions
        tele_birr_ratio = ((customer_df['source'] == 'TELE BIRR INCOMING') | 
                          (customer_df['source'] == 'TELE BIRR OUT GOING')).sum() / total_transactions
        
        features.extend([unique_sources, most_common_source_ratio, cash_deposit_ratio, 
                        fund_transfer_ratio, cash_withdraw_ratio, tele_birr_ratio])
        
        # Temporal patterns
        customer_df['date'] = pd.to_datetime(customer_df['date'])
        
        # Time of day patterns
        avg_hour = customer_df['date'].dt.hour.mean()
        hour_std = customer_df['date'].dt.hour.std()
        night_transactions = ((customer_df['date'].dt.hour >= 22) | 
                            (customer_df['date'].dt.hour <= 6)).sum() / total_transactions
        
        features.extend([avg_hour, hour_std, night_transactions])
        
        # Day of week patterns
        weekday_transactions = (customer_df['date'].dt.dayofweek < 5).sum() / total_transactions
        weekend_transactions = (customer_df['date'].dt.dayofweek >= 5).sum() / total_transactions
        
        features.extend([weekday_transactions, weekend_transactions])
        
        # Transaction frequency patterns
        if total_transactions > 1:
            time_diffs = customer_df['date'].sort_values().diff().dt.total_seconds() / 3600  # hours
            avg_time_between_transactions = time_diffs.mean()
            min_time_between_transactions = time_diffs.min()
            max_time_between_transactions = time_diffs.max()
        else:
            avg_time_between_transactions = 0
            min_time_between_transactions = 0
            max_time_between_transactions = 0
            
        features.extend([avg_time_between_transactions, min_time_between_transactions, 
                        max_time_between_transactions])
        
        # Narrative patterns
        avg_narrative_length = customer_df['narrative'].str.len().mean()
        unique_narratives = customer_df['narrative'].nunique()
        narrative_diversity = unique_narratives / total_transactions
        
        features.extend([avg_narrative_length, unique_narratives, narrative_diversity])
        
        # Balance ratio patterns
        balance_ratios = np.where(customer_df['closingBalance'] > 0, 
                                transaction_amounts / customer_df['closingBalance'], 0)
        avg_balance_ratio = balance_ratios.mean()
        max_balance_ratio = balance_ratios.max()
        balance_ratio_volatility = balance_ratios.std()
        
        features.extend([avg_balance_ratio, max_balance_ratio, balance_ratio_volatility])
        
        # Risk indicators
        high_amount_transactions = (np.abs(transaction_amounts) > transaction_amounts.quantile(0.9)).sum() / total_transactions
        rapid_transactions = (time_diffs < 1).sum() / max(total_transactions - 1, 1) if total_transactions > 1 else 0
        
        features.extend([high_amount_transactions, rapid_transactions])
        
        customer_features.append(features)
    
    print(f"Generated customer-level features for {len(customer_ids)} customers")
    print(f"Feature count per customer: {len(customer_features[0]) if customer_features else 0}")
    
    return np.array(customer_features), customer_ids


def prepare_business_features(df: pd.DataFrame) -> np.ndarray:
    """Extract business features from the actual generated data structure"""
    features = []
    
    # Establishment year
    features.append(df['business_establishment_year'].values)
    
    # Business sector encoding
    sector_mapping = {
        'AGRICULTURE': 0, 'MANUFACTURING': 1, 'DOMESTIC_TRADE_SERVICES': 2,
        'SERVICES': 3, 'OTHER': 4
    }
    sector_encoded = df['business_sector'].map(sector_mapping).fillna(-1)
    features.append(sector_encoded.values)
    
    # Business level encoding
    level_mapping = {'GROWING': 0, 'STARTUP': 1}
    level_encoded = df['business_level'].map(level_mapping).fillna(-1)
    features.append(level_encoded.values)
    
    # Starting capital
    features.append(df['business_starting_capital'].values)
    
    # Current capital
    features.append(df['business_current_capital'].values)
    
    # Annual profit
    features.append(df['business_annual_profit'].values)
    
    # Annual sales
    features.append(df['business_annual_sales'].values)
    
    # Starting employees
    features.append(df['business_starting_no_of_employees'].values)
    
    # Current employees
    features.append(df['business_current_no_of_employees'].values)
    
    # Source of initial capital encoding
    source_mapping = {
        'FAMILY': 0, 'OWN': 1, 'LOAN': 2, 'FUND': 3, 'OTHER': 4
    }
    source_encoded = df['business_source_of_initial_capital'].map(source_mapping).fillna(-1)
    features.append(source_encoded.values)
    
    # Association type encoding
    association_mapping = {
        'SOLE_PROPRIETORSHIP': 0, 'PARTNERSHIP': 1, 'CORPORATION': 2, 'OTHER': 3
    }
    association_encoded = df['business_association_type'].map(association_mapping).fillna(-1)
    features.append(association_encoded.values)
    
    # Derived features
    # Capital growth ratio
    capital_growth = np.where(df['business_starting_capital'] > 0,
                            df['business_current_capital'] / df['business_starting_capital'],
                            0)
    features.append(capital_growth)
    
    # Employee growth ratio
    employee_growth = np.where(df['business_starting_no_of_employees'] > 0,
                             df['business_current_no_of_employees'] / df['business_starting_no_of_employees'],
                             0)
    features.append(employee_growth)
    
    # Profit margin
    profit_margin = np.where(df['business_annual_sales'] > 0,
                           df['business_annual_profit'] / df['business_annual_sales'],
                           0)
    features.append(profit_margin)
    
    # Business age (years since establishment)
    current_year = 2024
    business_age = current_year - df['business_establishment_year']
    features.append(business_age.values)
    
    return np.column_stack(features)


def train_model(X: np.ndarray, model_type: str):
    """
    Train Isolation Forest model
    
    Args:
        X: Feature matrix
        model_type: 'kyc' or 'transaction'
    """
    print(f"\nTraining {model_type} model...")
    print(f"Training samples: {X.shape[0]}, Features: {X.shape[1]}")
    
    # Scale features
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    # Train Isolation Forest
    model = IsolationForest(
        contamination=settings.CONTAMINATION,
        random_state=settings.RANDOM_STATE,
        n_estimators=settings.N_ESTIMATORS,
        max_samples='auto',
        n_jobs=-1,
        verbose=1
    )
    
    model.fit(X_scaled)
    
    # Get predictions and scores for evaluation
    predictions = model.predict(X_scaled)
    scores = model.score_samples(X_scaled)
    
    anomaly_count = np.sum(predictions == -1)
    anomaly_pct = (anomaly_count / len(predictions)) * 100
    
    print("Training complete!")
    print(f"Anomalies detected: {anomaly_count} ({anomaly_pct:.2f}%)")
    print(f"Score range: [{scores.min():.3f}, {scores.max():.3f}]")
    
    return model, scaler, scores


def save_model(model, scaler, model_type: str):
    """Save model and scaler to disk"""
    models_dir = Path(settings.KYC_MODEL_PATH).parent
    models_dir.mkdir(parents=True, exist_ok=True)
    
    if model_type == 'kyc':
        model_path = settings.KYC_MODEL_PATH
        scaler_path = settings.KYC_SCALER_PATH
    elif model_type == 'business':
        model_path = str(models_dir / 'business_model.pkl')
        scaler_path = str(models_dir / 'business_scaler.pkl')
    elif model_type == 'merged':
        model_path = str(models_dir / 'merged_model.pkl')
        scaler_path = str(models_dir / 'merged_scaler.pkl')
    elif model_type == 'customer':
        model_path = str(models_dir / 'customer_model.pkl')
        scaler_path = str(models_dir / 'customer_scaler.pkl')
    else:  # transaction
        model_path = settings.TRANSACTION_MODEL_PATH
        scaler_path = settings.TRANSACTION_SCALER_PATH
    
    joblib.dump(model, model_path)
    joblib.dump(scaler, scaler_path)
    
    print(f"\nModel saved to: {model_path}")
    print(f"Scaler saved to: {scaler_path}")


def evaluate_model(model, scaler, X: np.ndarray):
    """Evaluate model performance"""
    X_scaled = scaler.transform(X)
    predictions = model.predict(X_scaled)
    scores = model.score_samples(X_scaled)
    
    print("\n=== Model Evaluation ===")
    print(f"Total samples: {len(predictions)}")
    print(f"Normal: {np.sum(predictions == 1)}")
    print(f"Anomalies: {np.sum(predictions == -1)}")
    print(f"Anomaly rate: {(np.sum(predictions == -1) / len(predictions)) * 100:.2f}%")
    print(f"Score statistics:")
    print(f"  Mean: {scores.mean():.3f}")
    print(f"  Std: {scores.std():.3f}")
    print(f"  Min: {scores.min():.3f}")
    print(f"  Max: {scores.max():.3f}")


def main():
    parser = argparse.ArgumentParser(description='Train anomaly detection models')
    parser.add_argument('--kyc-data', type=str, help='Path to KYC training data CSV')
    parser.add_argument('--business-data', type=str, help='Path to business training data CSV')
    parser.add_argument('--transaction-data', type=str, help='Path to transaction training data CSV')
    parser.add_argument('--merged-data', type=str, help='Path to merged KYC+Business data CSV')
    parser.add_argument('--train-kyc', action='store_true', help='Train KYC model')
    parser.add_argument('--train-business', action='store_true', help='Train business model')
    parser.add_argument('--train-transaction', action='store_true', help='Train transaction model')
    parser.add_argument('--train-merged', action='store_true', help='Train merged KYC+Business model')
    parser.add_argument('--train-customer', action='store_true', help='Train customer-level model')
    
    args = parser.parse_args()
    
    if not any([args.train_kyc, args.train_business, args.train_transaction, args.train_merged, args.train_customer]):
        print("Please specify at least one training option:")
        print("  --train-kyc")
        print("  --train-business")
        print("  --train-transaction")
        print("  --train-merged")
        print("  --train-customer")
        return
    
    # Train KYC model
    if args.train_kyc:
        if not args.kyc_data:
            print("Error: --kyc-data required for training KYC model")
            return

        print("=" * 50)
        print("TRAINING KYC MODEL")
        print("=" * 50)
        
        df = load_training_data(args.kyc_data, 'kyc')
        X = prepare_kyc_features(df)
        model, scaler, scores = train_model(X, 'kyc')
        evaluate_model(model, scaler, X)
        save_model(model, scaler, 'kyc')
    
    # Train Business model
    if args.train_business:
        if not args.business_data:
            print("Error: --business-data required for training business model")
            return

        print("\n" + "=" * 50)
        print("TRAINING BUSINESS MODEL")
        print("=" * 50)
        
        df = load_training_data(args.business_data, 'business')
        X = prepare_business_features(df)
        model, scaler, scores = train_model(X, 'business')
        evaluate_model(model, scaler, X)
        save_model(model, scaler, 'business')
    
    # Train Transaction model
    if args.train_transaction:
        if not args.transaction_data:
            print("Error: --transaction-data required for training transaction model")
            return

        print("\n" + "=" * 50)
        print("TRAINING TRANSACTION MODEL")
        print("=" * 50)
        
        df = load_training_data(args.transaction_data, 'transaction')
        X = prepare_transaction_features(df)
        model, scaler, scores = train_model(X, 'transaction')
        evaluate_model(model, scaler, X)
        save_model(model, scaler, 'transaction')
    
    # Train Merged KYC+Business model
    if args.train_merged:
        if not args.merged_data:
            print("Error: --merged-data required for training merged model")
            return

        print("\n" + "=" * 50)
        print("TRAINING MERGED KYC+BUSINESS MODEL")
        print("=" * 50)
        
        df = load_training_data(args.merged_data, 'merged')
        
        # Combine KYC and Business features
        kyc_features = prepare_kyc_features(df)
        business_features = prepare_business_features(df)
        X = np.column_stack([kyc_features, business_features])
        
        model, scaler, scores = train_model(X, 'merged')
        evaluate_model(model, scaler, X)
        save_model(model, scaler, 'merged')
    
    # Train Customer model
    if args.train_customer:
        if not args.transaction_data:
            print("Error: --transaction-data required for training customer model")
            return

        print("\n" + "=" * 50)
        print("TRAINING CUSTOMER MODEL")
        print("=" * 50)
        
        df = load_training_data(args.transaction_data, 'customer')
        X, customer_ids = prepare_customer_features(df)
        model, scaler, scores = train_model(X, 'customer')
        evaluate_model(model, scaler, X)
        save_model(model, scaler, 'customer')
    
    print("\n" + "=" * 50)
    print("TRAINING COMPLETE!")
    print("=" * 50)


def train_all_models():
    """Convenience function to train all models for hackathon demo"""
    print("=" * 60)
    print("TRAINING ALL MODELS FOR HACKATHON DEMO")
    print("=" * 60)
    
    # Check if data files exist
    data_dir = Path("data/raw")
    kyc_path = data_dir / "kyc_training_data.csv"
    business_path = data_dir / "business_training_data.csv"
    merged_path = data_dir / "kyc_business_training_data.csv"
    transaction_path = data_dir / "transaction_training_data.csv"
    
    if not data_dir.exists():
        print("Error: data/raw directory not found. Please run generate_synthetic_data.py first.")
        return
    
    # Train KYC model
    if kyc_path.exists():
        print("\n[1/4] Training KYC model...")
        df = load_training_data(str(kyc_path), 'kyc')
        X = prepare_kyc_features(df)
        model, scaler, scores = train_model(X, 'kyc')
        evaluate_model(model, scaler, X)
        save_model(model, scaler, 'kyc')
    else:
        print(f"Warning: {kyc_path} not found, skipping KYC model")
    
    # Train Business model
    if business_path.exists():
        print("\n[2/4] Training Business model...")
        df = load_training_data(str(business_path), 'business')
        X = prepare_business_features(df)
        model, scaler, scores = train_model(X, 'business')
        evaluate_model(model, scaler, X)
        save_model(model, scaler, 'business')
    else:
        print(f"Warning: {business_path} not found, skipping Business model")
    
    # Train Merged model
    if merged_path.exists():
        print("\n[3/4] Training Merged KYC+Business model...")
        df = load_training_data(str(merged_path), 'merged')
        kyc_features = prepare_kyc_features(df)
        business_features = prepare_business_features(df)
        X = np.column_stack([kyc_features, business_features])
        model, scaler, scores = train_model(X, 'merged')
        evaluate_model(model, scaler, X)
        save_model(model, scaler, 'merged')
    else:
        print(f"Warning: {merged_path} not found, skipping Merged model")
    
    # Train Transaction model
    if transaction_path.exists():
        print("\n[4/5] Training Transaction model...")
        df = load_training_data(str(transaction_path), 'transaction')
        X = prepare_transaction_features(df)
        model, scaler, scores = train_model(X, 'transaction')
        evaluate_model(model, scaler, X)
        save_model(model, scaler, 'transaction')
    else:
        print(f"Warning: {transaction_path} not found, skipping Transaction model")
    
    # Train Customer model
    if transaction_path.exists():
        print("\n[5/5] Training Customer model...")
        df = load_training_data(str(transaction_path), 'customer')
        X, customer_ids = prepare_customer_features(df)
        model, scaler, scores = train_model(X, 'customer')
        evaluate_model(model, scaler, X)
        save_model(model, scaler, 'customer')
    else:
        print(f"Warning: {transaction_path} not found, skipping Customer model")
    
    print("\n" + "=" * 60)
    print("ALL MODELS TRAINING COMPLETE!")
    print("=" * 60)
    print("Models are ready for the hackathon demo!")


if __name__ == "__main__":
    import sys
    if len(sys.argv) == 1:
        # No arguments provided, run demo mode
        train_all_models()
    else:
        # Arguments provided, run normal mode
        main()